pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: ./HtmlCopyVSCode.sln
  outDir: $(Build.ArtifactStagingDirectory)

steps:
- script: dotnet build $(sln) -c $(buildConfiguration) -o $(outDir) /nologo /p:GeneratePackageOnBuild=True
  displayName: 'dotnet build $(buildConfiguration)'
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))